### ISSUE TITLE
Hierarchical specifications

### ISSUE THREAD

**Issue by tyarkoni** [grabbles/grabbit#17]
Currently grabbit assumes that all folders/files below the project root obey the same spec. For a variety of reasons, it would be good to allow hierarchical specifications, so that on the initial scan, each folder would be checked for its own .json spec, and if one is found, the entities defined within that file will be used for any files below. Internally, it's probably best to handle this by initializing multiple `Layout` objects and maintaining a common index across them (to enable returning of files that match entities shared across specs).

**Comment by adelavega** [comment]
It might be useful to allow users to blacklist the indexing of certain folders (such as 'derivatives/' in the case of pybids). This is useful when there are many folders that do *not* follow the spec, but it slows down indexing.

From a user standpoint, what would be ideal is if you could blacklist folders from being indexed, unless they contain their own json spec. 

One implementation would be to allow blacklisting folders for the main Layout, then allow hierarchical specifications, but with a depth flag (e.g. only 2 deep), to minimize excessive indexing. Thus, if a folder with its own spec is found (even if in an originally blacklisted folder), a new Layout would be created for that folder. 

I'm happy to work on this by the way.

**Comment by tyarkoni** [comment]
Yeah, this would be good. Blacklisting should probably be a separate issue though. And also not a high priority, so probably keep working on the neuroscout back-end for now (if you want to add an `exclude` flag to the init that just drops files if they match regex patterns in a string or list, that's fine, but the hierarchical stuff is more work than it's worth at the moment).

**Comment by tyarkoni** [comment]
Per discussion at BIDS hackathon, the `exclude_dirs` argument to init should be replaced with a new `"index"` section in the JSON config file that has both `"include"` and `"exclude"` sections listing regex paths to include or exclude.
