### ISSUE TITLE
Write out, and reconstruct Layout from, index file

### ISSUE THREAD

**Issue by tyarkoni** [grabbles/grabbit#28]
Currently grabbit constructs the full file index at initialization time, after scanning the entire project directory. This is inefficient, and also rules out important use cases (e.g., in DataLad) where there's a need to run queries on a project even though the file names and/or contents aren't locally available. We should add methods to (a) write out a generic, plaintext representation of the internal index, and (b) allow construction of the `Layout` object from a saved file.

**Comment by mih** [comment]
Many thanks! Finally looking into this from the DataLad POV...

**Comment by tyarkoni** [comment]
Cool, make sure you read the discussion in #30 for explanation of some of the design choices. Changes are of course still possible if something I've done doesn't work for you guys.
