### ISSUE TITLE
Return entities in natural order

### ISSUE THREAD

**Issue by chrisfilo** [grabbles/grabbit#3]
https://www.wikiwand.com/en/Natural_sort_order

**Comment by tyarkoni** [comment]
Would be easy to do, but the question is what fields to natsort on. Filename? Entity ID? In cases where the user requests the `return_type` of 'dir' or 'id', this is straightforward; what do we do for 'tuple' or 'file'?)

Also, do you have a preferred natsort implementation? I usually use [natsort](https://pypi.python.org/pypi/natsort), but that seems a bit heavy to bundle, and it would be nice to stick to the no-dependency policy. I found [this implementation](http://stackoverflow.com/a/4836734/2445984) on SO, which seems to work pretty well.

**Comment by chrisfilo** [comment]
In case of Files we should order on filename. When one can get tuples?

I don't have a favourite natsort implementation, but my favourite color is
blue. No yello... Auuuuuuuugh!

**Comment by tyarkoni** [comment]
See if [this](https://github.com/grabbles/grabbit/tree/add-natsort) suits your needs. Looks good to me and all tests pass.

**Comment by tyarkoni** [comment]
Oh, and the default `return_type` is namedtuples. We probably don't need to be returning `File` instances anyway. I could make `return_type='file'` return *only* the filenames; that seems like a reasonable thing to want.
