### ISSUE TITLE
"parse_file_entities" unintended behavior with domain = None

### ISSUE THREAD

**Issue by adelavega** [grabbles/grabbit#66]
When domain is not specified to `parse_file_entities`, there are a few bugs

    target = '/datasets/SherlockMerlin/derivatives/fmriprep/sub-37/func/sub-37_task-MerlinMovie_run-1_bold_space-MNI152NLin2009cAsym_preproc.nii.gz'   
    bids_dir = '/datasets/SherlockMerlin'
    preproc_dir = '/datasets/SherlockMerlin/derivatives/fmriprep`  
    layout = BIDSLayout(bids_dir, config=[('bids', bids_dir), ('derivatives', preproc_dir)])  

The following both return the same output:

    layout.files[fname].entities 
    layout.parse_file_entities(target, domains=['bids'])  
    {'subject': '37',  'task': 'MerlinMovie' 'run': '1', 'type': 'preproc', 'modality': 'func'}  

So far so good, but:

    layout.parse_file_entities(target, domains=None)  

First, this will fail because it tries to loop over `None` domains. Fixing that however, the result is `{}`. Because of how this function works, however, the original file will be ovewritten in the file index, so calling with `domains=['bids']` afterwards will also return `{}`.

Probably the easy fix here is to default to a domain, and not allow None, since that will simply create an empty file object and replace the original contents in the index.

**Comment by adelavega** [comment]
Not as far as I can tell. This function is not inherited/reimplemented in pybids

**Comment by adelavega** [comment]
Not as far as I can tell. It's a grabbit issue not a pybids issue in anycase, as this function is not inherited and implemented in pybids.

**Comment by tyarkoni** [comment]
Oh, sorry--I didn't see that we're talking about `parse_file_entities`.

**Comment by tyarkoni** [comment]
Okay yeah, this is an easy bug to fix. Will push a patch shortly.
